resources:
  - name: docker_Build_vijay
    type: BuildInfo
    configuration:
      sourceArtifactory: vijay_art
      buildNumber: 1
      buildName: dockertest
      
  - name: docker_build_promote_vijay
    type: BuildInfo
    configuration:
      sourceArtifactory: vijay_art
      buildNumber: 1
      buildName: dockertest
      
  - name: dockerbuild_vijay
    type: GitRepo
    configuration:
      path: vijayreddy1991/nativesteps
      gitProvider: vijay_git
      branches:
        include: docker
        
pipelines:
  - name: docker_vijay
    steps:
      - name: dockerBuild
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: '34.68.55.176:8082/docker-local/pipelines'
          dockerImageTag: '${run_number}'
          integrations:
            - name: vijay_art
          inputResources:
            - name: dockerbuild_vijay
        execution:
          onStart:
            - echo "hi"
            - docker images
            - printenv
            - ls -la
          onSuccess:
            - docker images
      - name: dockerPush
        type: DockerPush
        configuration:
          targetRepository: docker-local
          integrations:
            - name: vijay_art
          inputSteps:
            - name: dockerBuild
      - name: dockerPublish
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: dockerPush
          outputResources:
            - name: docker_Build_vijay
      - name: dockerPromote
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          inputSteps:
            - name: dockerPublish
          integrations:
            - name: vijay_art
          inputResources:
            - name: docker_Build_vijay
          outputResources:
            - name: docker_build_promote_vijay
            
            



            
            
