resources:
  - name: docker_Build_abhishek
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildNumber: 1
      buildName: dockertest
      
  - name: docker_build_promote_abhishek
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildNumber: 1
      buildName: dockertest
      
  - name: dockerbuild_abhishek
    type: GitRepo
    configuration:
      path: abhishek325/nativesteps
      gitProvider: abhishek_github
      branches:
        include: docker
        
pipelines:
  - name: docker_abhishek
    steps:
      - name: dockerBuild
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
#           dockerImageName: 'c8testrt.jfrog-pipelines.com/pipelines/api/docker-local/pipelines'
#           dockerImageName: 'rhel8rt.jfrog-pipelines.com/docker-local/pipelines'
#           dockerImageName: 'pipelines.westus.cloudapp.azure.com:8082/docker-local/pipelines'
          dockerImageName: 'pipe-master.jfrog.info:8082/docker-local/node'
#           dockerImageName: 'u20.jfrog-pipelines.com/docker-local/pipelines'
          dockerImageTag: '${run_number}'
          integrations:
            - name: art_v
          inputResources:
            - name: dockerbuild_abhishek
        execution:
          onStart:
            - echo "hi"
            - docker images
            - printenv
            - ls -la
          onSuccess:
            - docker images
      - name: dockerPush
        type: DockerPush
        configuration:
          targetRepository: docker-local
          integrations:
            - name: art_v
          inputSteps:
            - name: dockerBuild
            
#       - name: dockerPublish
#         type: PublishBuildInfo
#         configuration:
#           inputSteps:
#             - name: dockerPush
#           outputResources:
#             - name: dockerbuild_vijay
            
#       - name: dockerPromote
#         type: PromoteBuild
#         configuration:
#           targetRepository: test-generic-local
#           inputSteps:
#             - name: dockerPublish
#           integrations:
#             - name: art_v
#           inputResources:
#             - name: dockerbuild_

#           outputResources:
#             - name: docker_build_promote_vijay
            
            



            
            
