pipelines:
  - name: pipelines_vijay
    steps:
      - name: vijay1
        type: Jenkins
        configuration:
          jenkinsJobName: var-pipeline-proj    # Jenkins job/pipeline name. required
          priority: 1
          buildParameters:
            key1: 1
            key2: 2
          integrations:
            - name: jenkins

      - name: vijay2
        type: Jenkins
        configuration:
          jenkinsJobName: var-pipeline-proj   # Jenkins job/pipeline name. required
          priority: 2
          buildParameters:
            key1: 1
            key2: 2
          integrations:
            - name: jenkins
          inputSteps:
            - name : vijay1
